var sb="<!-- 顶部 -->";
 sb=sb+"      <div class=\"header\" node-type=\"header\">";
 sb=sb+"        <div class=\"appinfo\">";
 sb=sb+"          <div class=\"header_box\"><img node-type=\"head\"></div>";
 sb=sb+"          <h1><a node-type=\"title\" href=\"#\"></a></h1>";
 sb=sb+"          <p class=\"welcomemsg\" node-type=\"welcome\"></p>";
 sb=sb+"        </div>";
 sb=sb+"        <a title=\"%{robottag_close}\" class=\"robot_icon_close\" node-type=\"close_btn\"></a>";
 sb=sb+"        <a title=\"%{robottag_adjust_window}\" node-type=\"max_btn\"></a>";
 sb=sb+"        <a title=\"%{robottag_manual_work}\" class=\"robot_icon_service\" node-type=\"service_btn\"></a>";
 sb=sb+"      </div>";
 sb=sb+"        ";
 sb=sb+"      <!-- 内容-->";
 sb=sb+"      <div class=\"robot_chat_layout\">";
 sb=sb+"      ";
 sb=sb+"        <!-- 聊天框 -->";
 sb=sb+"        <div class=\"chat_box\" node-type=\"chat_box\">";
 sb=sb+"          <div class=\"main_wrap\">";
 sb=sb+"            <!--聊天面板-->";
 sb=sb+"            <div class=\"chatpanel\" node-type=\"chatpanel\"></div>";
 sb=sb+"            <!--输入面板-->";
 sb=sb+"            <div class=\"inputpanel\" node-type=\"inputpanel\">";
 sb=sb+"              <textarea class=\"input_text\" type=\"text\" node-type=\"input_text\" placeholder=\"%{robottag_describe_problem}\"/>";
 sb=sb+"              <div class=\"input_count_box\">";
 sb=sb+"                <i class=\"ask_icon\"></i>%{robottag_enter}<em node-type=\"input_count\">30</em>%{robottag_word}";
 sb=sb+"              </div>";
 sb=sb+"              <a class=\"robot_icon_send\" node-type=\"send_btn\"></a>";
 sb=sb+"            </div>";
 sb=sb+"          </div>";
 sb=sb+"        </div>";
 sb=sb+"        ";
 sb=sb+"        <!-- 右侧 -->";
 sb=sb+"        <div class=\"col_sub appside\" node-type=\"attach_box\">";
 sb=sb+"          <div class=\"skin_side\">";
 sb=sb+"                <!--热点问题-->";
 sb=sb+"                <div class=\"box\">";
 sb=sb+"                  <div class=\"hd hdext\" node-type=\"ext_hot_head\"><h3>%{robottag_hot_issues}</h3></div>";
 sb=sb+"                  <div class=\"bd\" node-type=\"ext_hot_box\"><div class=\"exthot\" node-type=\"ext_hot\"><ul></ul></div></div>";
 sb=sb+"                </div>";
 sb=sb+"                <!--相关内容-->";
 sb=sb+"                <div class=\"box\">";
 sb=sb+"                  <div class=\"hd\" node-type=\"ext_about_head\"><h3>%{robottag_related_issues}</h3></div>";
 sb=sb+"                  <div class=\"bd extabout\" node-type=\"ext_about_box\"><div class=\"exthot\" node-type=\"ext_about\">";
 sb=sb+"                  	<ul><p style='text-align:center;'>%{robottag_norelated_issues}</p></ul>";
 sb=sb+"                  </div></div>";
 sb=sb+"                </div>";
 sb=sb+"         </div>";
 sb=sb+"       </div>";
 sb=sb+"       ";
 sb=sb+"       <!-- <div class=\"drag_icon\" name=\"drag_icon\"></div> -->";
 sb=sb+"    </div>";