var webim_tag3 = '';
webim_tag3 += '<div id="wbim_box" class="wbim_box">';
webim_tag3 += '	<div node-type="wbim_list_expand" class="wbim_list_expand">';
webim_tag3 += '		';
webim_tag3 += '		<!-- 右侧在线状态、好友列表等 -->';
webim_tag3 += '		<div>';
webim_tag3 += '		  <!-- 顶部在线状态、搜索等  -->';
webim_tag3 += '			<div class="wbim_tit" node-type="wbim_titin" id="wbim_titin_id">';
webim_tag3 += '					<!-- 在线状态 -->';
webim_tag3 += '					<div class="wbim_tit_lf">';
webim_tag3 += '						<div node-type="status_manager" class="tit">';
webim_tag3 += '						  <!-- 当前状态 -->';
webim_tag3 += '							<span node-type="wbim_status_tit">';
webim_tag3 += '								 <span class="wbim_status_online"/>';
webim_tag3 += '								 <span class="txt">%{webimtag3_online}</span>';
webim_tag3 += '						    </span>';
webim_tag3 += '						  <!-- 下拉箭头 -->';
webim_tag3 += '						    <span node-type="wbim_status_tit_arrow" class="wbim_status_tit_arrow"/>';
webim_tag3 += '						  <!-- 下拉列表 -->';
webim_tag3 += '						    <ul node-type="wbim_status_list">';
webim_tag3 += '                                <li data-status="1" class="wbim_status_selected">';
webim_tag3 += '                                    <a href="javascript:void(0)"><span class="wbim_status_online"></span>';
webim_tag3 += '                                        <span class="wbim_status_label" node-type="wbim_status_label">%{webimtag3_online}</span>';
webim_tag3 += '                                    </a>';
webim_tag3 += '                                </li>';
webim_tag3 += '                                <li data-status="2">';
webim_tag3 += '                                    <a href="javascript:void(0)"><span class="wbim_status_busy"></span>';
webim_tag3 += '                                        <span class="wbim_status_label" node-type="wbim_status_label">%{webimtag3_bebusy}</span>';
webim_tag3 += '                                    </a>';
webim_tag3 += '                                </li>';
webim_tag3 += '                            </ul>';
webim_tag3 += '						</div>';
webim_tag3 += '					</div>';
webim_tag3 += '					';
webim_tag3 += '					<!-- 搜索 -->';
webim_tag3 += '					<div class="wbim_list_up">';
webim_tag3 += '					   <input id="wbim_search" type="text" /><!-- 搜索框 -->';
webim_tag3 += '					   <div class="wbim_list_srch_icon" /><!-- 图标 -->';
webim_tag3 += '		            </div>';
webim_tag3 += '					';
webim_tag3 += '					<!-- 最小化 -->';
webim_tag3 += '					<a node-type="wbim_icon_mini" title="%{webimtag3_mini}" class="wbim_icon_mini" href="javascript:;"></a>';
webim_tag3 += '			</div>';
webim_tag3 += '			<!-- <div class="wbim_line"></div>  -->';
webim_tag3 += '			';
webim_tag3 += '			<!-- 好友、群聊、最近联系人标签 -->';
webim_tag3 += '			<div class="wbim_list_tab">';
webim_tag3 += '				<ul>';
webim_tag3 += '					<li title="%{webimtag3_mycontact_person}">';
webim_tag3 += '						%{webimtag3_mycontact_person}';
webim_tag3 += '					</li>';
webim_tag3 += '					<!--  ';
webim_tag3 += '					<li>';
webim_tag3 += '						<a title="%{webimtag3_group}" href="javascript:;"><span><em class="wbim_tab_group"></em></span></a>';
webim_tag3 += '					</li>';
webim_tag3 += '					-->';
webim_tag3 += '					<li title="%{webimtag3_recent_contact}">';
webim_tag3 += '						%{webimtag3_recent_contact}';
webim_tag3 += '					</li>';
webim_tag3 += '				</ul>';
webim_tag3 += '			</div>';
webim_tag3 += '			<div style="position:absolute;top:74px;left:2px;width:180px;height:31px;background-color:white;z-index:1;display:none;overflow:hidden;" class="wbim_float_group_tit"></div>';
webim_tag3 += '			<div class="wbim_list_box">';
webim_tag3 += '				<div node-type="wbim_list_friendlist" class="wbim_list_friend">';
webim_tag3 += '					<div class="wbim_list_nof"><span class="wbim_icon_tips"></span>%{webimtag3_notget_friends}</div>';
webim_tag3 += '				</div>';
webim_tag3 += '				<!-- ';
webim_tag3 += '				<div node-type="wbim_list_grouplist" class="wbim_list_friend" style="display: none;">';
webim_tag3 += '					<div class="wbim_list_nof"><span class="wbim_icon_tips"></span>%{webimtag3_notjoin_group}</div>';
webim_tag3 += '				</div>';
webim_tag3 += '				-->';
webim_tag3 += '				<div node-type="wbim_list_nearlist" class="wbim_list_friend" style="display: none;">';
webim_tag3 += '					<div class="wbim_list_nof"><span class="wbim_icon_tips"></span>%{webimtag3_norecent_contact}</div>';
webim_tag3 += '				</div>';
webim_tag3 += '				<div node-type="wbim_list_searchlist" class="wbim_list_friend" style="display: none;">';
webim_tag3 += '					<div class="wbim_list_nof"><span class="wbim_icon_tips"></span>%{webimtag3_nomatching_contact}</div>';
webim_tag3 += '				</div>';
webim_tag3 += '			</div>';
webim_tag3 += '			';
webim_tag3 += '			<!-- 底部收起按钮 -->';
webim_tag3 += '			<div class="wbim_list_pos"><a node-type="wbim_clicknone" href="javascript:;" class="wbim_clicknone"><span class="wbim_icon_arrd"></span></a>';
webim_tag3 += '                <!-- <div title="%{webimtag3_send_privateletter}" class="wbim_send_con"><a href="javascript:;" hidefocus="true" class="wbim_send_pmsg"><span class="wbim_btn_pmsg"></span></a></div> -->';
webim_tag3 += '            </div>';
webim_tag3 += '		</div>';
webim_tag3 += '	</div>';
webim_tag3 += '	<div id="wbim_chat_box" node-type="wbim_chat_box" class="wbim_chat_box wbim_chat_box_s">';
webim_tag3 += '		<div node-type="wbim_chat_con">';
webim_tag3 += '			<div id="wbim_chat_box_head" node-type="wbim_tit" class="wbim_tit">';
webim_tag3 += '			 <!-- 九宫格背景 ';
webim_tag3 += '			    <div class="wbim_tit_bg">';
webim_tag3 += '				    <div class="wbim_tit_bg_left"/>';
webim_tag3 += '	                <div class="wbim_tit_bg_middle"/>';
webim_tag3 += '	                <div class="wbim_tit_bg_right"/>';
webim_tag3 += '			    </div>';
webim_tag3 += '			 -->';
webim_tag3 += '			 <!-- 对方昵称和关闭按钮 -->';
webim_tag3 += '				<div node-type="wbim_titin" class="wbim_titin">';
webim_tag3 += '					<div class="wbim_tit_lf">';
webim_tag3 += '						<!-- 私聊  -->';
webim_tag3 += '						<p node-type="wbim_single_user" >';
webim_tag3 += '							<!-- 普通用户 -->';
webim_tag3 += '                            <span id="wbim_tit_lf_user_name_id" class="txt">';
webim_tag3 += '                                <a node-type="wbim_tit_lf_user_name" title="">&nbsp;</a>';
webim_tag3 += '                            </span>';
webim_tag3 += '                            <!-- 在线客服 -->';
webim_tag3 += '                            <span id="wbim_tit_lf_service_name_id" class="txt">';
webim_tag3 += '                                %{webimtag3_and}&nbsp;<label node-type="wbim_tit_lf_service_name" title="">&nbsp;</label>&nbsp;%{webimtag3_dialoguing}...';
webim_tag3 += '                            </span>';
webim_tag3 += '						</p>';
webim_tag3 += '						<!-- 群聊  -->';
webim_tag3 += '						<p node-type="wbim_group" style="display:none;">';
webim_tag3 += '							<span class="wbim_icon_group_tit"></span>';
webim_tag3 += '							<span class="txt">';
webim_tag3 += '								<a node-type="wbim_tit_lf_gname" target="_blank"></a>';
webim_tag3 += '								<em class="txtg">%{webimtag3_online_contact}(<a target="_blank" node-type="group_num" title="%{webimtag3_view_online}">';
webim_tag3 += '									</a>)';
webim_tag3 += '								</em>';
webim_tag3 += '							</span>';
webim_tag3 += '						</p>';
webim_tag3 += '					</div>';
webim_tag3 += '					';
webim_tag3 += '					<!-- 关闭聊天框 -->';
webim_tag3 += '					<div class="wbim_tit_rf">';
webim_tag3 += '					   <a node-type="wbim_btn_close" title="%{webimtag3_close}" hidefocus="true" class="wbim_icon_close" href="javascript:;"></a>';
webim_tag3 += '						<a node-type="wbim_icon_mini" title="%{webimtag3_mini}" hidefocus="true" class="wbim_icon_mini" href="javascript:;"></a>';
webim_tag3 += '					</div>';
webim_tag3 += '				</div>';
webim_tag3 += '			</div>';
webim_tag3 += '			';
webim_tag3 += '			<!-- 左侧好友列表 -->';
webim_tag3 += '			<div node-type="wbim_chat_lf" style="display:none;" class="wbim_chat_lf">';
webim_tag3 += '				<a href="javascript:;" node-type="wbim_scrolltop" class="wbim_scrolltop_n"></a>';
webim_tag3 += '				<div node-type="wbim_chat_friend_box" class="wbim_chat_friend_box">';
webim_tag3 += '					<ul id="wbim_chat_friend_list" node-type="wbim_chat_friend_list" class="wbim_chat_friend_list">';
webim_tag3 += '					</ul>';
webim_tag3 += '				</div>';
webim_tag3 += '				<a href="javascript:;" node-type="wbim_scrollbtm" class="wbim_scrollbtm_n"></a>';
webim_tag3 += '			</div>';
webim_tag3 += '			';
webim_tag3 += '			<div class="wbim_chat_rt">';
webim_tag3 += '			<div class="wbim_chat_up">';
webim_tag3 += '			 <!-- 对方不在线提醒 -->';
webim_tag3 += '                <div node-type="wbim_chat_tips" class="wbim_chat_tips" style="display: none;">';
webim_tag3 += '                    <span class="wbim_icon_tips"></span>';
webim_tag3 += '                    <span node-type="wbim_chat_tips_content" class="wbim_chat_tips_content"></span>';
webim_tag3 += '                    <a class="wbim_icon_close_s" node-type="wbim_icon_close_s" href="javascript:;" hidefocus="true"></a>';
webim_tag3 += '                </div>';
webim_tag3 += '			 <!-- 消息接收框 -->';
webim_tag3 += '				<div node-type="wbim_chat_list" class="wbim_chat_list"></div>';
webim_tag3 += '			</div>';
webim_tag3 += '';
webim_tag3 += '				<!-- 中间一栏(表情、上传图片和上传文件等) -->';
webim_tag3 += '				<div node-type="wbim_chat_toolbar" class="wbim_chat_toolbar">';
webim_tag3 += '					<div node-type="wbim_chat_toolbarin" class="wbim_chat_toolbarin">';
webim_tag3 += '					';
webim_tag3 += '						<!-- 基本表情 -->';
webim_tag3 += '						<div node-type="wbim_face" class="wbim_face">';
webim_tag3 += '							<a  node-type="wbim_icon_face" title="%{webimtag3_general_expression}"> ';
webim_tag3 += '								<i class="wbim_icon_face"/>%{webimtag3_expression}';
webim_tag3 += '							</a>';
webim_tag3 += '							<div node-type="wbim_face_box" style="display:none;" class="wbim_face_box">';
webim_tag3 += '								<div class="wbim_face_tit">';
webim_tag3 += '									<!-- <div class="wbim_face_arr" style="top:221px;left:8px;"></div> -->';
webim_tag3 += '									<div class="wbim_face_tit_lf">%{webimtag3_chat_expression}</div>';
webim_tag3 += '									<a node-type="wbim_icon_face_close" class="wbim_icon_close"/>';
webim_tag3 += '								</div>';
webim_tag3 += '								<div class="wbim_face_con">';
webim_tag3 += '									<ul node-type="wbim_face_list" class="wbim_face_list">';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_smile}]"><img imgsrc="images/face/1.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_pie}]"><img imgsrc="images/face/2.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_color}]"><img imgsrc="images/face/3.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_frighten}]"><img imgsrc="images/face/4.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_complacent}]"><img imgsrc="images/face/5.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_shed_tears}]"><img imgsrc="images/face/6.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_pudency}]"><img imgsrc="images/face/7.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_shutup}]"><img imgsrc="images/face/8.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_sleep}]"><img imgsrc="images/face/9.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_cry}]"><img imgsrc="images/face/10.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_embarrassed}]"><img imgsrc="images/face/11.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_angry}]"><img imgsrc="images/face/12.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_naughty}]"><img imgsrc="images/face/13.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_bared_teeth}]"><img imgsrc="images/face/14.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_surprised}]"><img imgsrc="images/face/15.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_sorry}]"><img imgsrc="images/face/16.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_cool}]"><img imgsrc="images/face/17.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_cold_sweat}]"><img imgsrc="images/face/18.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_crazy}]"><img imgsrc="images/face/19.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_spit}]"><img imgsrc="images/face/20.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_laughing}]"><img imgsrc="images/face/21.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_lovely}]"><img imgsrc="images/face/22.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_roll_eyes}]"><img imgsrc="images/face/23.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_arrogant}]"><img imgsrc="images/face/24.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_hungry}]"><img imgsrc="images/face/25.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_tired}]"><img imgsrc="images/face/26.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_terrified}]"><img imgsrc="images/face/27.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_perspire}]"><img imgsrc="images/face/28.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_gelasmus}]"><img imgsrc="images/face/29.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_soldier}]"><img imgsrc="images/face/30.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_struggle}]"><img imgsrc="images/face/31.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_curse}]"><img imgsrc="images/face/32.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_doubt}]"><img imgsrc="images/face/33.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_hush}]"><img imgsrc="images/face/34.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_giddy}]"><img imgsrc="images/face/35.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_torture}]"><img imgsrc="images/face/36.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_decline}]"><img imgsrc="images/face/37.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_skeleton}]"><img imgsrc="images/face/38.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_beat}]"><img imgsrc="images/face/39.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_bye}]"><img imgsrc="images/face/40.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_sweat}]"><img imgsrc="images/face/41.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_pull_nose}]"><img imgsrc="images/face/42.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_applause}]"><img imgsrc="images/face/43.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_big_qiu}]"><img imgsrc="images/face/44.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_bad_smile}]"><img imgsrc="images/face/45.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_zuo_hengheng}]"><img imgsrc="images/face/46.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_you_hengheng}]"><img imgsrc="images/face/47.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_yawn}]"><img imgsrc="images/face/48.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_despise}]"><img imgsrc="images/face/49.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_grievance}]"><img imgsrc="images/face/50.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_gonna_cry}]"><img imgsrc="images/face/51.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_sinister}]"><img imgsrc="images/face/52.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_kiss}]"><img imgsrc="images/face/53.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_stupefied}]"><img imgsrc="images/face/54.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_poor}]"><img imgsrc="images/face/55.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_strong}]"><img imgsrc="images/face/56.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_weak}]"><img imgsrc="images/face/57.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_ok}]"><img imgsrc="images/face/58.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_handshake}]"><img imgsrc="images/face/59.gif"></a></li>';
webim_tag3 += '										<li><a href="javascript:;" title="[%{webimtag3_victory}]"><img imgsrc="images/face/60.gif"></a></li>';
webim_tag3 += '									</ul>';
webim_tag3 += '									<div class="tsina_loading cter">';
webim_tag3 += '										<span class="tsina_ico_ldg"></span>';
webim_tag3 += '									</div>';
webim_tag3 += '								</div>';
webim_tag3 += '							</div>';
webim_tag3 += '						</div>';
webim_tag3 += '						';
webim_tag3 += '						<!-- 上传图片 -->';
webim_tag3 += '						<div class="wbim_face" title="%{webimtag3_upload_pic}">';
webim_tag3 += '							<a hidefocus="true" node-type="wbim_icon_img"> ';
webim_tag3 += '								<i class="wbim_icon_img"/>%{webimtag3_pic}';
webim_tag3 += '							</a>';
webim_tag3 += '						</div>';
webim_tag3 += '						';
webim_tag3 += '						<!-- 上传文件 -->';
webim_tag3 += '						<div class="wbim_face" title="%{webimtag3_upload_file}">';
webim_tag3 += '							<a hidefocus="true" node-type="wbim_icon_doc"> ';
webim_tag3 += '								<i class="wbim_icon_doc"/>%{webimtag3_file}';
webim_tag3 += '							</a>';
webim_tag3 += '						</div>';
webim_tag3 += '						';
webim_tag3 += '						<!-- 提示音 -->';
webim_tag3 += '						<div class="wbim_face" title="%{webimtag3_sound_cue}">';
webim_tag3 += '							<a  node-type="wbim_icon_voice"> ';
webim_tag3 += '								<i class="wbim_icon_voice"/>%{webimtag3_sound_cue}';
webim_tag3 += '							</a>';
webim_tag3 += '						</div>';
webim_tag3 += '						';
webim_tag3 += '						<!-- 常用语 -->';
webim_tag3 += '						<div node-type="wbim_quick" class="wbim_face">';
webim_tag3 += '							<a title="%{webimtag3_common_language}" style="display: none;" node-type="wbim_icon_quick">';
webim_tag3 += '							     <i class="wbim_icon_quick"/>%{webimtag3_common_language}';
webim_tag3 += '							</a>';
webim_tag3 += '							<div node-type="wbim_quick_box" style="display: none;" class="wbim_quick_box">';
webim_tag3 += '								<div class="wbim_quick_tit">';
webim_tag3 += '									<div node-type="wbim_quick_tit_lf" class="wbim_quick_tit_lf">%{webimtag3_common_language}</div>';
webim_tag3 += '									<a node-type="wbim_icon_quick_close" class="wbim_icon_close"/>';
webim_tag3 += '								</div>';
webim_tag3 += '								<div node-type="wbim_quick_con" class="wbim_quick_con">';
webim_tag3 += '								</div>';
webim_tag3 += '							</div>';
webim_tag3 += '						</div>';
webim_tag3 += '						';
webim_tag3 += '						<!-- 打分邀请 -->';
webim_tag3 += '						<div node-type="wbim_ping" class="wbim_face">';
webim_tag3 += '							<a title="%{webimtag3_scoring_invitation}" style="display: none;" node-type="wbim_icon_ping">';
webim_tag3 += '							     <i class="wbim_icon_ping"/>%{webimtag3_invitation_score}';
webim_tag3 += '							</a>';
webim_tag3 += '							<div node-type="wbim_ping_box" style="display: none;" class="wbim_ping_box">';
webim_tag3 += '								<div class="wbim_ping_tit">';
webim_tag3 += '									<div node-type="wbim_ping_tit_lf" class="wbim_ping_tit_lf">%{webimtag3_service_score}</div>';
webim_tag3 += '									<a node-type="wbim_icon_ping_close" class="wbim_icon_close"/>';
webim_tag3 += '								</div>';
webim_tag3 += '								<div class="wbim_ping_con">';
webim_tag3 += '									<ul>';
webim_tag3 += '										<li>';
webim_tag3 += '											<input type="radio" name="pingscore" value="1" id="wbim_ping_bumanyi">';
webim_tag3 += '											<label for="wbim_ping_bumanyi">&nbsp;%{webimtag3_dissatisfied}</label>';
webim_tag3 += '										</li>';
webim_tag3 += '										<li>';
webim_tag3 += '											<input type="radio" name="pingscore" value="2" checked="checked" id="wbim_ping_manyi">';
webim_tag3 += '											<label for="wbim_ping_manyi">&nbsp;%{webimtag3_satisfied}</label>';
webim_tag3 += '										</li>';
webim_tag3 += '										<li>';
webim_tag3 += '											<input type="radio" name="pingscore" value="3" id="wbim_ping_fcmanyi">';
webim_tag3 += '											<label for="wbim_ping_fcmanyi">&nbsp;%{webimtag3_very_satisfied}</label>';
webim_tag3 += '										</li>';
webim_tag3 += '									</ul>';
webim_tag3 += '									<p class="wbim_ping_close">';
webim_tag3 += '										<a title="%{webimtag3_confirm}" class="wbim_btn_confirm" node-type="wbim_btn_confirm">%{webimtag3_confirm}</a>';
webim_tag3 += '									</p>';
webim_tag3 += '								</div>';
webim_tag3 += '							</div>';
webim_tag3 += '						</div>';
webim_tag3 += '						';
webim_tag3 += '						<!-- 订单查询 -->';
webim_tag3 += '						<div node-type="wbim_chaxun" class="wbim_face">';
webim_tag3 += '							<a title="%{webimtag3_order_query}" style="display: none;" node-type="wbim_icon_chaxun">';
webim_tag3 += '							     <i class="wbim_list_srch_icon"/>%{webimtag3_order_query}';
webim_tag3 += '							</a>';
webim_tag3 += '						</div>';
webim_tag3 += '						 ';
webim_tag3 += '						<!-- 聊天记录 -->';
webim_tag3 += '						<div node-type="wbim_history_cont"> ';
webim_tag3 += '							<!-- 聊天记录按钮 -->';
webim_tag3 += '							<a title="%{webimtag3_dialogue_log}" node-type="wbim_history" class="wbim_history">';
webim_tag3 += '								<i class="wbim_icon_chatdoc" />%{webimtag3_dialogue_log}';
webim_tag3 += '							</a>';
webim_tag3 += '							<!-- 聊天记录窗体 -->';
webim_tag3 += '							<div node-type="wbim_history_box" class="wbim_history_box" style="display: none;z-index:1000;">';
webim_tag3 += '								<div class="wbim_history_tit">';
webim_tag3 += '									<!-- <div class="wbim_face_arr" style="top:221px;left:8px;"></div> -->';
webim_tag3 += '									<div class="wbim_history_tit_lf" node-type="wbim_history_tit_lf"/>';
webim_tag3 += '									<a node-type="wbim_icon_history_close" href="javascript:;" class="wbim_icon_close"/>';
webim_tag3 += '								</div>';
webim_tag3 += '								<div node-type="wbim_history_con"/>';
webim_tag3 += '								<div class="wbim_history_btns">';
webim_tag3 += '									<p style="float:left;">';
webim_tag3 += '										<a node-type="wbim_history_refresh" href="javascript:void(0)">%{webimtag3_refresh}</a>';
webim_tag3 += '									</p>';
webim_tag3 += '									<p style="float: right;">';
webim_tag3 += '										<a node-type="wbim_history_next" href="javascript:void(0)">%{webimtag3_previous_page}</a>';
webim_tag3 += '										<a node-type="wbim_history_prev" href="javascript:void(0)">%{webimtag3_next_page}</a>';
webim_tag3 += '										<span class="wbim_history_ii">';
webim_tag3 += '											<input type="text" id="wbim_history_ii" value="0"/>';
webim_tag3 += '										</span>';
webim_tag3 += '										<span>/</span>';
webim_tag3 += '										<span node-type="wbim_history_max">0</span>';
webim_tag3 += '										<a node-type="wbim_history_query_btn" href="javascript:void(0)">%{webimtag3_confirm}</a>';
webim_tag3 += '									</p>';
webim_tag3 += '								</div>';
webim_tag3 += '							</div>';
webim_tag3 += '						</div> ';
webim_tag3 += '						<!---->  ';
webim_tag3 += '						';
webim_tag3 += '					</div>';
webim_tag3 += '				</div>';
webim_tag3 += '';
webim_tag3 += '				<!-- 输入框、删除上上传的文件按钮等 -->';
webim_tag3 += '				<div style="margin-top:1px;" node-type="wbim_chat_input" class="wbim_chat_input wbim_chat_input_dis">';
webim_tag3 += '					<!-- 删除上上传的文件按钮  -->';
webim_tag3 += '					<div node-type="root" class="wbim_chat_input_tips" style="display: none;">';
webim_tag3 += '						<div style="display: none;" node-type="wbim_tips_pic" class="wbim_tips_pos_n">';
webim_tag3 += '							<div class="wbim_tips_pic_n"><a href="javascript:;">';
webim_tag3 += '								<a href="javascript:;">';
webim_tag3 += '									<img style="cursor:pointer" action-type="wbim_img_preview" node-type="img_preview">';
webim_tag3 += '								</a>';
webim_tag3 += '							</div>';
webim_tag3 += '							<span class="wbim_p_arr"/>';
webim_tag3 += '						</div>';
webim_tag3 += '						<div id="fls" node-type="fl" class="fl">';
webim_tag3 += '							<span class="icon_ing" style="display:none;"/>';
webim_tag3 += '							<span class="wbim_icon_s_photo" style="display:none;"/>';
webim_tag3 += '							<p id="upFileNameId"/>';
webim_tag3 += '						</div>';
webim_tag3 += '						<div node-type="fr" class="fr">';
webim_tag3 += '							<a id="vdiskId" href="http://vdisk.weibo.com/file/list#3" target="_blank" class="links" style="display:none;" suda-uatrack="key=tblog_webim_behavior&amp;value=view_vdisk" node-type="vdisk">%{webimtag3_mymicro_disk}</a>';
webim_tag3 += '							<a id="deleteFileId" style="display:none;" node-type="deleteFile" class="links">%{webimtag3_delete}</a>';
webim_tag3 += '						</div>';
webim_tag3 += '					</div>';
webim_tag3 += '					<!-- 输入框 -->';
webim_tag3 += '					<textarea node-type="wbim_chat_input_ta"/>';
webim_tag3 += '					<textarea id="fileUpTextId" style="display:none;"/>';
webim_tag3 += '				</div>';
webim_tag3 += '				';
webim_tag3 += '				<!-- 最底下一栏(结束对话、发送等) -->';
webim_tag3 += '				<div node-type="wbim_chat_btm" class="wbim_chat_btm">';
webim_tag3 += '					<div node-type="wbim_chat_btmin" class="wbim_chat_btmin">';
webim_tag3 += '						<p class="wbim_tips_char">';
webim_tag3 += '						      %{webimtag3_input}<span style="font-size:22px" node-type="wbim_tips_char">200</span>%{webimtag3_word}';
webim_tag3 += '						</p>';
webim_tag3 += '						<div class="wbim_chat_btm_rt">';
webim_tag3 += '							<div node-type="wbim_btn_send" id="webimBtnSendDivId" class="wbim_btn_send wbim_btn_send_disable"><a id="webimBtnSendId" class="wbim_btn_publish" node-type="wbim_btn_publish">%{webimtag3_send}</a>';
webim_tag3 += '								<div class="wbim_btn_choose">';
webim_tag3 += '									<a class="wbim_btn_choose_a" node-type="wbim_btn_choose_a">%{webimtag3_choice}</a>';
webim_tag3 += '									<ul node-type="wbim_btn_choose" style="display: none;">';
webim_tag3 += '										<li node-type="wbim_enter_send_li" class="curr"><span><i></i></span><em><a node-type="wbim_enter_send" href="javascript:;">%{webimtag3_enter}</a></em></li>';
webim_tag3 += '										<li class="line"><span></span><em></em></li>';
webim_tag3 += '										<li class="" node-type="wbim_ctrlenter_send_li"><span><i></i></span><em><a node-type="wbim_ctrlenter_send" href="javascript:;">%{webimtag3_ctrl_enter}</a></em></li>';
webim_tag3 += '									</ul>';
webim_tag3 += '								</div>';
webim_tag3 += '							</div>';
webim_tag3 += '						</div>';
webim_tag3 += '					</div>';
webim_tag3 += '				</div>';
webim_tag3 += '		</div>';
webim_tag3 += '		';
webim_tag3 += '		<div id="im_sidebar_container" style="float:left;">';
webim_tag3 += '			<div class="im-right-sidebar">';
webim_tag3 += '		  		<div class="im-shop-service">';
webim_tag3 += '		 	  		 <ul id="im-tab" class="im-tab">';
webim_tag3 += '		 	  			  <li class="current" id="im-tab-li_0" onclick="ChangeDiv(\'im-tab-li_\',\'0\',\'id_\',2)"><span>%{webimtag3_archives_info}</span></li>';
webim_tag3 += '		 	  			  <li id="im-tab-li_1" onclick="ChangeDiv(\'im-tab-li_\',\'1\',\'id_\',2)"><span>%{webimtag3_order_info}</span></li>';
webim_tag3 += '		  	  		 </ul>';
webim_tag3 += '		 	  	 	 <div id="im-tab-contents" class="im-tab-contents">';
webim_tag3 += '		 	   			<div id="id_0" class="im-tab-content">';
webim_tag3 += '							<!----档案信息：im-product-info---->';
webim_tag3 += '		 	   				<div class="im-product-info marginT10 marginLR10" id="sidebar_baseInfo"></div>';
webim_tag3 += '		 	   			</div>';
webim_tag3 += '		 	   			<div id="id_1" class="im-tab-content" style="display:none;">';
webim_tag3 += '							<!----订单信息-im-shop-info---->';
webim_tag3 += '		 	   				<div class="im-shop-info marginT10 marginLR10" id="sidebar_orderInfo"></div>';
webim_tag3 += '		 	   			</div>';
webim_tag3 += '		  	 	     </div>';
webim_tag3 += '		 		 </div>';
webim_tag3 += '			</div>';
webim_tag3 += '		</div>';
webim_tag3 += '';
webim_tag3 += '	</div>';
webim_tag3 += '    </div>';
webim_tag3 += '	';
webim_tag3 += '	';
webim_tag3 += '	<div node-type="wbim_min_box_col" class="wbim_min_box_col2" style="position: absolute; bottom: 0px; right: 0px;z-index:1;">';
webim_tag3 += '		<div class="wbim_min_box">';
webim_tag3 += '			';
webim_tag3 += '			<!-- 打开的聊天框最小化  -->';
webim_tag3 += '			<div node-type="wbim_min_chat" class="wbim_min_chat"><span class="wbim_icon_msg"></span><span node-type="wbim_min_tipbar" style="display:none;">%{webimtag3_new_msg}</span><span node-type="wbim_min_chatuserbar"><span class="wbim_min_text_pre" style="display: inline;">%{webimtag3_and} </span><span node-type="wbim_min_nick" class="wbim_min_nick">&nbsp;</span><span class="line"></span><span class="wbim_min_text">%{webimtag3_dialoguing}</span></span></div>';
webim_tag3 += '		    <!-- 分割线 -->';
webim_tag3 += '		    <div class="wbim_min_line wbim_min_linefor3"></div>';
webim_tag3 += '		    <!-- 最小化图标 -->';
webim_tag3 += '		    <div node-type="wbim_min_friend" class="wbim_min_friend">';
webim_tag3 += '                <div node-type="wbim_sys_btncon" class="wbim_sys_btncon" title="%{webimtag3_sys_msg}"><a node-type="wbim_sys_btn" class="wbim_btn_sysbtn" href="javascript:;"><span node-type="wbim_btn_sysmsg" class="wbim_btn_sysmsg"></span></a></div>';
webim_tag3 += '                <p node-type="wbim_statusbox" class="statusbox"><span class="wbim_status_online" style="float:left;"></span></p>';
webim_tag3 += '                %{webimtag3_dialogue} [ <span node-type="wbim_online_count" class="wbim_online_count" title="%{webimtag3_online_contact}">0</span> ]';
webim_tag3 += '            </div>';
webim_tag3 += '            ';
webim_tag3 += '		</div>';
webim_tag3 += '	</div>';
webim_tag3 += '	<div node-type="wbim_sys_msg" style="display: none;" class="wbim_sys_msg">';
webim_tag3 += '		<div class="wbim_sys_tit">';
webim_tag3 += '			<div class="wbim_sys_tit_lf" node-type="wbim_sys_tit_lf">%{webimtag3_sys_msg}</div>';
webim_tag3 += '			<a node-type="wbim_icon_sys_close" style="float:right;" href="javascript:;" class="wbim_icon_close"></a>';
webim_tag3 += '		</div>';
webim_tag3 += '		<div class="wbim_sys_con" node-type="wbim_sys_con">';
webim_tag3 += '			<dl node-type="wbim_sys_dl"></dl>';
webim_tag3 += '		</div>';
webim_tag3 += '	</div>';
webim_tag3 += '	<div class="wbim_picview_box" node-type="wbim_tips_pos" style="bottom: auto; position: absolute; z-index: 1200; right: 300px; background-color: rgb(243, 243, 243); display: none;">';
webim_tag3 += '		<div class="wbim_img_con">';
webim_tag3 += '			<div class="wbim_pic_bar" node-type="wbim_pic_bar">';
webim_tag3 += '				<!-- ';
webim_tag3 += '				<div class="wbim_p_ctrl">';
webim_tag3 += '					<a class="wbim_plft" node-type="turn_left" title="向左转" href="javascript:void(0)" hidefocus="true"></a>';
webim_tag3 += '					<span class="wbim_vline">|</span>';
webim_tag3 += '					<a class="wbim_prgt" node-type="turn_right" title="向右转" href="javascript:void(0)" hidefocus="true"></a>';
webim_tag3 += '				</div>';
webim_tag3 += '				-->';
webim_tag3 += '				<div class="wbim_ptit">';
webim_tag3 += '						<span id="wbim_ptit_id"></span>';
webim_tag3 += '				</div>';
webim_tag3 += '				<a class="wbim_pic_bar_cls" node-type="wbim_icon_close_s" title="%{webimtag3_close}" href="javascript:closeImgZone();" hidefocus="true"></a>';
webim_tag3 += '			</div>';
webim_tag3 += '			<div id="wbim_pic_zoneId" class="wbim_pic_zone" />';
webim_tag3 += '		</div>';
webim_tag3 += '	</div>';
webim_tag3 += '	<!-- ';
webim_tag3 += '		<div style="position: absolute; z-index: 1500; overflow: hidden; width: 95px; height: 18px; bottom: 119px; right: 360px;">';
webim_tag3 += '			<embed id="swf_8575" width="95" height="18" flashvars="swfid=1747004125&maxSumSize=50&maxFileSize=50&maxFileNum=1&multiSelect=0&uploadAPI=http%3A%2F%2Fupload.api.weibo.com%2F2%2Fmss%2Fupload.json%3Fsource%3D209678993%26tuid%3D1887188824&initFun=STK.wbim.ui.Upload.initFun&sucFun=STK.wbim.ui.Upload.sucFun&errFun=STK.wbim.ui.Upload.errFun&beginFun=STK.wbim.ui.Upload.beginFun&areaInfo=0-40|10-40&fExt=*.jpg;*.gif;*.jpeg;*.png|*&fExtDec=选择图片|选择文件" data="upload.swf" wmode="transparent" bgcolor="" allowscriptaccess="always" allowfullscreen="true" scale="noScale" menu="false" type="application/x-shockwave-flash" src="http://service.weibo.com/staticjs/tools/upload.swf?v=ef8070fdd05ab2a8">';
webim_tag3 += '		</div>';
webim_tag3 += '	-->';
webim_tag3 += '	 ';
webim_tag3 += '</div>';
