var webim_tag4="<div id=\"wbim_box\" class=\"wbim_box\">";
 webim_tag4=webim_tag4+"	<div node-type=\"wbim_list_expand\" class=\"wbim_list_expand\">";
 webim_tag4=webim_tag4+"		";
 webim_tag4=webim_tag4+"		<!-- 右侧在线状态、好友列表等 -->";
 webim_tag4=webim_tag4+"		<div>";
 webim_tag4=webim_tag4+"		  <!-- 顶部在线状态、搜索等  -->";
 webim_tag4=webim_tag4+"			<div class=\"wbim_tit\" node-type=\"wbim_titin_dcp\" id=\"wbim_titin_id\">";
 webim_tag4=webim_tag4+"					<!-- 在线状态 -->";
 webim_tag4=webim_tag4+"					<div class=\"wbim_tit_lf\">";
 webim_tag4=webim_tag4+"						<div node-type=\"status_manager\" class=\"tit\">";
 webim_tag4=webim_tag4+"						  <!-- 当前状态 -->";
 webim_tag4=webim_tag4+"							<span node-type=\"wbim_status_tit\">";
 webim_tag4=webim_tag4+"								 <span class=\"wbim_status_online\"/>";
 webim_tag4=webim_tag4+"								 <span class=\"txt\">在线</span>";
 webim_tag4=webim_tag4+"						    </span>";
 webim_tag4=webim_tag4+"						  <!-- 下拉箭头 -->";
 webim_tag4=webim_tag4+"						    <span node-type=\"wbim_status_tit_arrow\" class=\"wbim_status_tit_arrow\"/>";
 webim_tag4=webim_tag4+"						  <!-- 下拉列表 -->";
 webim_tag4=webim_tag4+"						    <ul node-type=\"wbim_status_list\">";
 webim_tag4=webim_tag4+"                                <li data-status=\"1\" class=\"wbim_status_selected\">";
 webim_tag4=webim_tag4+"                                    <a href=\"javascript:void(0)\"><span class=\"wbim_status_online\"></span>";
 webim_tag4=webim_tag4+"                                        <span class=\"wbim_status_label\" node-type=\"wbim_status_label\">在线</span>";
 webim_tag4=webim_tag4+"                                    </a>";
 webim_tag4=webim_tag4+"                                </li>";
 webim_tag4=webim_tag4+"                                <li data-status=\"2\">";
 webim_tag4=webim_tag4+"                                    <a href=\"javascript:void(0)\"><span class=\"wbim_status_busy\"></span>";
 webim_tag4=webim_tag4+"                                        <span class=\"wbim_status_label\" node-type=\"wbim_status_label\">忙碌</span>";
 webim_tag4=webim_tag4+"                                    </a>";
 webim_tag4=webim_tag4+"                                </li>";
 webim_tag4=webim_tag4+"                            </ul>";
 webim_tag4=webim_tag4+"						</div>";
 webim_tag4=webim_tag4+"					</div>";
 webim_tag4=webim_tag4+"					";
 webim_tag4=webim_tag4+"					<!-- 搜索 -->";
 webim_tag4=webim_tag4+"					<div class=\"wbim_list_up\">";
 webim_tag4=webim_tag4+"					   <input id=\"wbim_search\" type=\"text\" /><!-- 搜索框 -->";
 webim_tag4=webim_tag4+"					   <div class=\"wbim_list_srch_icon\" /><!-- 图标 -->";
 webim_tag4=webim_tag4+"		            </div>";
 webim_tag4=webim_tag4+"					";
 webim_tag4=webim_tag4+"					<!-- 最小化 ";
 webim_tag4=webim_tag4+"					<a node-type=\"wbim_icon_mini\" title=\"最小化\" class=\"wbim_icon_mini\" href=\"javascript:;\"></a>";
 webim_tag4=webim_tag4+"					-->";
 webim_tag4=webim_tag4+"			</div>";
 webim_tag4=webim_tag4+"			<!-- <div class=\"wbim_line\"></div>  -->";
 webim_tag4=webim_tag4+"			";
 webim_tag4=webim_tag4+"			<!-- 好友、群聊、最近联系人标签 -->";
 webim_tag4=webim_tag4+"			<div class=\"wbim_list_tab\">";
 webim_tag4=webim_tag4+"				<ul>";
 webim_tag4=webim_tag4+"					<li title=\"我的联系人\">";
 webim_tag4=webim_tag4+"						我的联系人";
 webim_tag4=webim_tag4+"					</li>";
 webim_tag4=webim_tag4+"					<!--  ";
 webim_tag4=webim_tag4+"					<li>";
 webim_tag4=webim_tag4+"						<a title=\"群组\" href=\"javascript:;\"><span><em class=\"wbim_tab_group\"></em></span></a>";
 webim_tag4=webim_tag4+"					</li>";
 webim_tag4=webim_tag4+"					-->";
 webim_tag4=webim_tag4+"					<li title=\"最近联系人\">";
 webim_tag4=webim_tag4+"						最近联系人";
 webim_tag4=webim_tag4+"					</li>";
 webim_tag4=webim_tag4+"				</ul>";
 webim_tag4=webim_tag4+"			</div>";
 webim_tag4=webim_tag4+"			<div style=\"position:absolute;top:74px;left:2px;width:180px;height:31px;background-color:white;z-index:1;display:none;overflow:hidden;\" class=\"wbim_float_group_tit\"></div>";
 webim_tag4=webim_tag4+"			<div class=\"wbim_list_box\">";
 webim_tag4=webim_tag4+"				<div node-type=\"wbim_list_friendlist\" class=\"wbim_list_friend\">";
 webim_tag4=webim_tag4+"					<div class=\"wbim_list_nof\"><span class=\"wbim_icon_tips\"></span>尚未获取到好友列表</div>";
 webim_tag4=webim_tag4+"				</div>";
 webim_tag4=webim_tag4+"				<!-- ";
 webim_tag4=webim_tag4+"				<div node-type=\"wbim_list_grouplist\" class=\"wbim_list_friend\" style=\"display: none;\">";
 webim_tag4=webim_tag4+"					<div class=\"wbim_list_nof\"><span class=\"wbim_icon_tips\"></span>您还没有加入群</div>";
 webim_tag4=webim_tag4+"				</div>";
 webim_tag4=webim_tag4+"				-->";
 webim_tag4=webim_tag4+"				<div node-type=\"wbim_list_nearlist\" class=\"wbim_list_friend\" style=\"display: none;\">";
 webim_tag4=webim_tag4+"					<div class=\"wbim_list_nof\"><span class=\"wbim_icon_tips\"></span>没有最近联系人</div>";
 webim_tag4=webim_tag4+"				</div>";
 webim_tag4=webim_tag4+"				<div node-type=\"wbim_list_searchlist\" class=\"wbim_list_friend\" style=\"display: none;\">";
 webim_tag4=webim_tag4+"					<div class=\"wbim_list_nof\"><span class=\"wbim_icon_tips\"></span>没有找到符合条件的联系人</div>";
 webim_tag4=webim_tag4+"				</div>";
 webim_tag4=webim_tag4+"			</div>";
 webim_tag4=webim_tag4+"			";
 webim_tag4=webim_tag4+"		</div>";
 webim_tag4=webim_tag4+"	</div>";
 webim_tag4=webim_tag4+"	<div id=\"wbim_chat_box\" node-type=\"wbim_chat_box\" class=\"wbim_chat_box wbim_chat_box_s\">";
 webim_tag4=webim_tag4+"		<div node-type=\"wbim_chat_con\">";
 webim_tag4=webim_tag4+"			<div id=\"wbim_chat_box_head\" node-type=\"wbim_tit\" class=\"wbim_tit\">";
 webim_tag4=webim_tag4+"			 <!-- 九宫格背景 ";
 webim_tag4=webim_tag4+"			    <div class=\"wbim_tit_bg\">";
 webim_tag4=webim_tag4+"				    <div class=\"wbim_tit_bg_left\"/>";
 webim_tag4=webim_tag4+"	                <div class=\"wbim_tit_bg_middle\"/>";
 webim_tag4=webim_tag4+"	                <div class=\"wbim_tit_bg_right\"/>";
 webim_tag4=webim_tag4+"			    </div>";
 webim_tag4=webim_tag4+"			 -->";
 webim_tag4=webim_tag4+"			 <!-- 对方昵称和关闭按钮 -->";
 webim_tag4=webim_tag4+"				<div node-type=\"wbim_titin_dcp\" class=\"wbim_titin_dcp\">";
 webim_tag4=webim_tag4+"					<div class=\"wbim_tit_lf\">";
 webim_tag4=webim_tag4+"						<!-- 私聊  -->";
 webim_tag4=webim_tag4+"						<p node-type=\"wbim_single_user\" >";
 webim_tag4=webim_tag4+"							<!-- 普通用户 -->";
 webim_tag4=webim_tag4+"                            <span id=\"wbim_tit_lf_user_name_id\" class=\"txt\">";
 webim_tag4=webim_tag4+"                                <a node-type=\"wbim_tit_lf_user_name\" title=\"\">&nbsp;</a>";
 webim_tag4=webim_tag4+"                            </span>";
 webim_tag4=webim_tag4+"                            <!-- 在线客服 -->";
 webim_tag4=webim_tag4+"                            <span id=\"wbim_tit_lf_service_name_id\" class=\"txt\">";
 webim_tag4=webim_tag4+"                                与&nbsp;<a node-type=\"wbim_tit_lf_service_name\" title=\"\">&nbsp;</a>&nbsp;对话中...";
 webim_tag4=webim_tag4+"                            </span>";
 webim_tag4=webim_tag4+"						</p>";
 webim_tag4=webim_tag4+"						<!-- 群聊  -->";
 webim_tag4=webim_tag4+"						<p node-type=\"wbim_group\" style=\"display:none;\">";
 webim_tag4=webim_tag4+"							<span class=\"wbim_icon_group_tit\"></span>";
 webim_tag4=webim_tag4+"							<span class=\"txt\">";
 webim_tag4=webim_tag4+"								<a node-type=\"wbim_tit_lf_gname\" target=\"_blank\"></a>";
 webim_tag4=webim_tag4+"								<em class=\"txtg\">在线联系人(<a target=\"_blank\" node-type=\"group_num\" title=\"查看在线联系人\">";
 webim_tag4=webim_tag4+"									</a>)";
 webim_tag4=webim_tag4+"								</em>";
 webim_tag4=webim_tag4+"							</span>";
 webim_tag4=webim_tag4+"						</p>";
 webim_tag4=webim_tag4+"					</div>";
 webim_tag4=webim_tag4+"					<!-- 关闭聊天框 -->";
 webim_tag4=webim_tag4+"					<div class=\"wbim_tit_rf\">";
 webim_tag4=webim_tag4+"					   <a node-type=\"wbim_btn_close\" title=\"关闭\" hidefocus=\"true\" class=\"wbim_icon_close\" href=\"javascript:;\"></a>";
 webim_tag4=webim_tag4+"					</div>";
 webim_tag4=webim_tag4+"				</div>";
 webim_tag4=webim_tag4+"			</div>";
 webim_tag4=webim_tag4+"			";
 webim_tag4=webim_tag4+"			<!-- 左侧好友列表 -->";
 webim_tag4=webim_tag4+"			<div node-type=\"wbim_chat_lf\" style=\"display:none;\" class=\"wbim_chat_lf\">";
 webim_tag4=webim_tag4+"				<a href=\"javascript:;\" node-type=\"wbim_scrolltop\" class=\"wbim_scrolltop_n\"></a>";
 webim_tag4=webim_tag4+"				<div node-type=\"wbim_chat_friend_box\" class=\"wbim_chat_friend_box\">";
 webim_tag4=webim_tag4+"					<ul id=\"wbim_chat_friend_list\" node-type=\"wbim_chat_friend_list\" class=\"wbim_chat_friend_list\">";
 webim_tag4=webim_tag4+"					</ul>";
 webim_tag4=webim_tag4+"				</div>";
 webim_tag4=webim_tag4+"				<a href=\"javascript:;\" node-type=\"wbim_scrollbtm\" class=\"wbim_scrollbtm_n\"></a>";
 webim_tag4=webim_tag4+"			</div>";
 webim_tag4=webim_tag4+"			";
 webim_tag4=webim_tag4+"			<div class=\"wbim_chat_rt\">";
 webim_tag4=webim_tag4+"			<div class=\"wbim_chat_up\">";
 webim_tag4=webim_tag4+"			 <!-- 对方不在线提醒 -->";
 webim_tag4=webim_tag4+"                <div node-type=\"wbim_chat_tips\" class=\"wbim_chat_tips\" style=\"display: none;\">";
 webim_tag4=webim_tag4+"                    <span class=\"wbim_icon_tips\"></span>";
 webim_tag4=webim_tag4+"                    <span node-type=\"wbim_chat_tips_content\" class=\"wbim_chat_tips_content\"></span>";
 webim_tag4=webim_tag4+"                    <a class=\"wbim_icon_close_s\" node-type=\"wbim_icon_close_s\" href=\"javascript:;\" hidefocus=\"true\"></a>";
 webim_tag4=webim_tag4+"                </div>";
 webim_tag4=webim_tag4+"			 <!-- 消息接收框 -->";
 webim_tag4=webim_tag4+"				<div node-type=\"wbim_chat_list\" class=\"wbim_chat_list\"></div>";
 webim_tag4=webim_tag4+"			</div>";
 webim_tag4=webim_tag4+"";
 webim_tag4=webim_tag4+"				<!-- 中间一栏(表情、上传图片和上传文件等) -->";
 webim_tag4=webim_tag4+"				<div node-type=\"wbim_chat_toolbar\" class=\"wbim_chat_toolbar\">";
 webim_tag4=webim_tag4+"					<div node-type=\"wbim_chat_toolbarin\" class=\"wbim_chat_toolbarin\">";
 webim_tag4=webim_tag4+"					";
 webim_tag4=webim_tag4+"						<!-- 基本表情 -->";
 webim_tag4=webim_tag4+"						<div node-type=\"wbim_face\" class=\"wbim_face\">";
 webim_tag4=webim_tag4+"							<a  node-type=\"wbim_icon_face\" title=\"普通表情\"> ";
 webim_tag4=webim_tag4+"								<i class=\"wbim_icon_face\"/>表情";
 webim_tag4=webim_tag4+"							</a>";
 webim_tag4=webim_tag4+"							<div node-type=\"wbim_face_box\" style=\"display:none;\" class=\"wbim_face_box\">";
 webim_tag4=webim_tag4+"								<div class=\"wbim_face_tit\">";
 webim_tag4=webim_tag4+"									<!-- <div class=\"wbim_face_arr\" style=\"top:221px;left:8px;\"></div> -->";
 webim_tag4=webim_tag4+"									<div class=\"wbim_face_tit_lf\">聊天表情</div>";
 webim_tag4=webim_tag4+"									<a node-type=\"wbim_icon_face_close\" class=\"wbim_icon_close\"/>";
 webim_tag4=webim_tag4+"								</div>";
 webim_tag4=webim_tag4+"								<div class=\"wbim_face_con\">";
 webim_tag4=webim_tag4+"									<ul node-type=\"wbim_face_list\" class=\"wbim_face_list\">";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[微笑]\"><img imgsrc=\"images/face/1.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[撇嘴]\"><img imgsrc=\"images/face/2.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[色]\"><img imgsrc=\"images/face/3.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[发呆]\"><img imgsrc=\"images/face/4.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[得意]\"><img imgsrc=\"images/face/5.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[流泪]\"><img imgsrc=\"images/face/6.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[害羞]\"><img imgsrc=\"images/face/7.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[闭嘴]\"><img imgsrc=\"images/face/8.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[睡]\"><img imgsrc=\"images/face/9.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[大哭]\"><img imgsrc=\"images/face/10.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[尴尬]\"><img imgsrc=\"images/face/11.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[发怒]\"><img imgsrc=\"images/face/12.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[调皮]\"><img imgsrc=\"images/face/13.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[呲牙]\"><img imgsrc=\"images/face/14.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[惊讶]\"><img imgsrc=\"images/face/15.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[难过]\"><img imgsrc=\"images/face/16.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[酷]\"><img imgsrc=\"images/face/17.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[冷汗]\"><img imgsrc=\"images/face/18.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[抓狂]\"><img imgsrc=\"images/face/19.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[吐]\"><img imgsrc=\"images/face/20.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[偷笑]\"><img imgsrc=\"images/face/21.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[可爱]\"><img imgsrc=\"images/face/22.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[白眼]\"><img imgsrc=\"images/face/23.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[傲慢]\"><img imgsrc=\"images/face/24.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[饥饿]\"><img imgsrc=\"images/face/25.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[困]\"><img imgsrc=\"images/face/26.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[惊恐]\"><img imgsrc=\"images/face/27.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[流汗]\"><img imgsrc=\"images/face/28.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[憨笑]\"><img imgsrc=\"images/face/29.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[大兵]\"><img imgsrc=\"images/face/30.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[奋斗]\"><img imgsrc=\"images/face/31.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[咒骂]\"><img imgsrc=\"images/face/32.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[疑问]\"><img imgsrc=\"images/face/33.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[嘘]\"><img imgsrc=\"images/face/34.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[晕]\"><img imgsrc=\"images/face/35.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[折磨]\"><img imgsrc=\"images/face/36.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[衰]\"><img imgsrc=\"images/face/37.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[骷髅]\"><img imgsrc=\"images/face/38.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[敲打]\"><img imgsrc=\"images/face/39.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[再见]\"><img imgsrc=\"images/face/40.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[擦汗]\"><img imgsrc=\"images/face/41.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[抠鼻]\"><img imgsrc=\"images/face/42.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[鼓掌]\"><img imgsrc=\"images/face/43.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[糗大了]\"><img imgsrc=\"images/face/44.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[坏笑]\"><img imgsrc=\"images/face/45.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[左哼哼]\"><img imgsrc=\"images/face/46.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[右哼哼]\"><img imgsrc=\"images/face/47.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[哈欠]\"><img imgsrc=\"images/face/48.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[鄙视]\"><img imgsrc=\"images/face/49.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[委屈]\"><img imgsrc=\"images/face/50.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[快哭了]\"><img imgsrc=\"images/face/51.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[阴险]\"><img imgsrc=\"images/face/52.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[亲亲]\"><img imgsrc=\"images/face/53.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[吓]\"><img imgsrc=\"images/face/54.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[可怜]\"><img imgsrc=\"images/face/55.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[强]\"><img imgsrc=\"images/face/56.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[弱]\"><img imgsrc=\"images/face/57.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[OK]\"><img imgsrc=\"images/face/58.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[握手]\"><img imgsrc=\"images/face/59.gif\"></a></li>";
 webim_tag4=webim_tag4+"										<li><a href=\"javascript:;\" title=\"[胜利]\"><img imgsrc=\"images/face/60.gif\"></a></li>";
 webim_tag4=webim_tag4+"									</ul>";
 webim_tag4=webim_tag4+"									<div class=\"tsina_loading cter\">";
 webim_tag4=webim_tag4+"										<span class=\"tsina_ico_ldg\"></span>";
 webim_tag4=webim_tag4+"									</div>";
 webim_tag4=webim_tag4+"								</div>";
 webim_tag4=webim_tag4+"							</div>";
 webim_tag4=webim_tag4+"						</div>";
 webim_tag4=webim_tag4+"						";
 webim_tag4=webim_tag4+"						<!-- 上传图片 -->";
 webim_tag4=webim_tag4+"						<div class=\"wbim_face\" title=\"上传图片\">";
 webim_tag4=webim_tag4+"							<a hidefocus=\"true\" node-type=\"wbim_icon_img\"> ";
 webim_tag4=webim_tag4+"								<i class=\"wbim_icon_img\"/>图片";
 webim_tag4=webim_tag4+"							</a>";
 webim_tag4=webim_tag4+"						</div>";
 webim_tag4=webim_tag4+"						";
 webim_tag4=webim_tag4+"						<!-- 上传文件 -->";
 webim_tag4=webim_tag4+"						<div class=\"wbim_face\" title=\"上传文件\">";
 webim_tag4=webim_tag4+"							<a hidefocus=\"true\" node-type=\"wbim_icon_doc\"> ";
 webim_tag4=webim_tag4+"								<i class=\"wbim_icon_doc\"/>文件";
 webim_tag4=webim_tag4+"							</a>";
 webim_tag4=webim_tag4+"						</div>";
 webim_tag4=webim_tag4+"						";
 webim_tag4=webim_tag4+"						<!-- 常用语 -->";
 webim_tag4=webim_tag4+"						<div node-type=\"wbim_quick\" class=\"wbim_face\">";
 webim_tag4=webim_tag4+"							<a title=\"常用语\" style=\"display: none;\" node-type=\"wbim_icon_quick\">";
 webim_tag4=webim_tag4+"							     <i class=\"wbim_icon_quick\"/>常用语";
 webim_tag4=webim_tag4+"							</a>";
 webim_tag4=webim_tag4+"							<div node-type=\"wbim_quick_box\" style=\"display: none;\" class=\"wbim_quick_box\">";
 webim_tag4=webim_tag4+"								<div class=\"wbim_quick_tit\">";
 webim_tag4=webim_tag4+"									<div node-type=\"wbim_quick_tit_lf\" class=\"wbim_quick_tit_lf\">常用语</div>";
 webim_tag4=webim_tag4+"									<a node-type=\"wbim_icon_quick_close\" class=\"wbim_icon_close\"/>";
 webim_tag4=webim_tag4+"								</div>";
 webim_tag4=webim_tag4+"								<div node-type=\"wbim_quick_con\" class=\"wbim_quick_con\">";
 webim_tag4=webim_tag4+"									<ul>";
 webim_tag4=webim_tag4+"										<li><a>您好！有什么需要帮助的吗？</a></li>";
 webim_tag4=webim_tag4+"										<li><a>感谢您的参与！</a></li>";
 webim_tag4=webim_tag4+"										<li><a>非常感谢您的留言！我们会努力做得更好！</a></li>";
 webim_tag4=webim_tag4+"										<li><a>我们没有明白您的留言。麻烦您详细地叙述一下。</a></li>";
 webim_tag4=webim_tag4+"										<li><a>期待您的参与并诚请您多提宝贵建议！</a></li>";
 webim_tag4=webim_tag4+"										<li><a>请您与您的客户经理联系。</a></li>";
 webim_tag4=webim_tag4+"										<li><a>不客气。</a></li>";
 webim_tag4=webim_tag4+"										<li><a>^0^</a></li>";
 webim_tag4=webim_tag4+"									</ul>";
 webim_tag4=webim_tag4+"								</div>";
 webim_tag4=webim_tag4+"							</div>";
 webim_tag4=webim_tag4+"						</div>";
 webim_tag4=webim_tag4+"						";
 webim_tag4=webim_tag4+"						<!-- 打分邀请 -->";
 webim_tag4=webim_tag4+"						<div node-type=\"wbim_ping\" class=\"wbim_face\">";
 webim_tag4=webim_tag4+"							<a title=\"打分邀请\" style=\"display: none;\" node-type=\"wbim_icon_ping\">";
 webim_tag4=webim_tag4+"							     <i class=\"wbim_icon_ping\"/>邀请评分";
 webim_tag4=webim_tag4+"							</a>";
 webim_tag4=webim_tag4+"							<div node-type=\"wbim_ping_box\" style=\"display: none;\" class=\"wbim_ping_box\">";
 webim_tag4=webim_tag4+"								<div class=\"wbim_ping_tit\">";
 webim_tag4=webim_tag4+"									<div node-type=\"wbim_ping_tit_lf\" class=\"wbim_ping_tit_lf\">服务打分</div>";
 webim_tag4=webim_tag4+"									<a node-type=\"wbim_icon_ping_close\" class=\"wbim_icon_close\"/>";
 webim_tag4=webim_tag4+"								</div>";
 webim_tag4=webim_tag4+"								<div class=\"wbim_ping_con\">";
 webim_tag4=webim_tag4+"									<ul>";
 webim_tag4=webim_tag4+"										<li>";
 webim_tag4=webim_tag4+"											<input type=\"radio\" name=\"pingscore\" value=\"1\" id=\"wbim_ping_bumanyi\">";
 webim_tag4=webim_tag4+"											<label for=\"wbim_ping_bumanyi\">&nbsp;不满意</label>";
 webim_tag4=webim_tag4+"										</li>";
 webim_tag4=webim_tag4+"										<li>";
 webim_tag4=webim_tag4+"											<input type=\"radio\" name=\"pingscore\" value=\"2\" checked=\"checked\" id=\"wbim_ping_manyi\">";
 webim_tag4=webim_tag4+"											<label for=\"wbim_ping_manyi\">&nbsp;满意</label>";
 webim_tag4=webim_tag4+"										</li>";
 webim_tag4=webim_tag4+"										<li>";
 webim_tag4=webim_tag4+"											<input type=\"radio\" name=\"pingscore\" value=\"3\" id=\"wbim_ping_fcmanyi\">";
 webim_tag4=webim_tag4+"											<label for=\"wbim_ping_fcmanyi\">&nbsp;非常满意</label>";
 webim_tag4=webim_tag4+"										</li>";
 webim_tag4=webim_tag4+"									</ul>";
 webim_tag4=webim_tag4+"									<p class=\"wbim_ping_close\">";
 webim_tag4=webim_tag4+"										<a title=\"确定\" class=\"wbim_btn_confirm\" node-type=\"wbim_btn_confirm\">确定</a>";
 webim_tag4=webim_tag4+"									</p>";
 webim_tag4=webim_tag4+"								</div>";
 webim_tag4=webim_tag4+"							</div>";
 webim_tag4=webim_tag4+"						</div>";
 webim_tag4=webim_tag4+"						";
 webim_tag4=webim_tag4+"						<!-- 聊天记录 -->";
 webim_tag4=webim_tag4+"						<div node-type=\"wbim_history_cont\"> ";
 webim_tag4=webim_tag4+"							<!-- 聊天记录按钮 -->";
 webim_tag4=webim_tag4+"							<a title=\"聊天记录\" node-type=\"wbim_history\" class=\"wbim_history\">";
 webim_tag4=webim_tag4+"								<i class=\"wbim_icon_chatdoc\" />对话记录";
 webim_tag4=webim_tag4+"							</a>";
 webim_tag4=webim_tag4+"							<!-- 聊天记录窗体 -->";
 webim_tag4=webim_tag4+"							<div node-type=\"wbim_history_box\" class=\"wbim_history_box\" style=\"display: none;z-index:1000;\">";
 webim_tag4=webim_tag4+"								<div class=\"wbim_history_tit\">";
 webim_tag4=webim_tag4+"									<!-- <div class=\"wbim_face_arr\" style=\"top:221px;left:8px;\"></div> -->";
 webim_tag4=webim_tag4+"									<div class=\"wbim_history_tit_lf\" node-type=\"wbim_history_tit_lf\"/>";
 webim_tag4=webim_tag4+"									<a node-type=\"wbim_icon_history_close\" href=\"javascript:;\" class=\"wbim_icon_close\"/>";
 webim_tag4=webim_tag4+"								</div>";
 webim_tag4=webim_tag4+"								<div node-type=\"wbim_history_con\"/>";
 webim_tag4=webim_tag4+"								<div class=\"wbim_history_btns\">";
 webim_tag4=webim_tag4+"									<p style=\"float:left;\">";
 webim_tag4=webim_tag4+"										<a node-type=\"wbim_history_refresh\" href=\"javascript:void(0)\">刷新</a>";
 webim_tag4=webim_tag4+"									</p>";
 webim_tag4=webim_tag4+"									<p style=\"float: right;\">";
 webim_tag4=webim_tag4+"										<a node-type=\"wbim_history_next\" href=\"javascript:void(0)\">上一页</a>";
 webim_tag4=webim_tag4+"										<a node-type=\"wbim_history_prev\" href=\"javascript:void(0)\">下一页</a>";
 webim_tag4=webim_tag4+"										<span class=\"wbim_history_ii\">";
 webim_tag4=webim_tag4+"											<input type=\"text\" id=\"wbim_history_ii\" value=\"0\"/>/";
 webim_tag4=webim_tag4+"										</span>";
 webim_tag4=webim_tag4+"										<span node-type=\"wbim_history_max\">0</span>";
 webim_tag4=webim_tag4+"										<a node-type=\"wbim_history_query_btn\" href=\"javascript:void(0)\">确定</a>";
 webim_tag4=webim_tag4+"									</p>";
 webim_tag4=webim_tag4+"								</div>";
 webim_tag4=webim_tag4+"							</div>";
 webim_tag4=webim_tag4+"						</div> ";
 webim_tag4=webim_tag4+"						<!---->  ";
 webim_tag4=webim_tag4+"						";
 webim_tag4=webim_tag4+"					</div>";
 webim_tag4=webim_tag4+"				</div>";
 webim_tag4=webim_tag4+"";
 webim_tag4=webim_tag4+"				<!-- 输入框、删除上上传的文件按钮等 -->";
 webim_tag4=webim_tag4+"				<div style=\"margin-top:1px;\" node-type=\"wbim_chat_input\" class=\"wbim_chat_input wbim_chat_input_dis\">";
 webim_tag4=webim_tag4+"					<!-- 删除上上传的文件按钮  -->";
 webim_tag4=webim_tag4+"					<div node-type=\"root\" class=\"wbim_chat_input_tips\" style=\"display: none;\">";
 webim_tag4=webim_tag4+"						<div style=\"display: none;\" node-type=\"wbim_tips_pic\" class=\"wbim_tips_pos_n\">";
 webim_tag4=webim_tag4+"							<div class=\"wbim_tips_pic_n\"><a href=\"javascript:;\">";
 webim_tag4=webim_tag4+"								<a href=\"javascript:;\">";
 webim_tag4=webim_tag4+"									<img style=\"cursor:pointer\" action-type=\"wbim_img_preview\" node-type=\"img_preview\">";
 webim_tag4=webim_tag4+"								</a>";
 webim_tag4=webim_tag4+"							</div>";
 webim_tag4=webim_tag4+"							<span class=\"wbim_p_arr\"/>";
 webim_tag4=webim_tag4+"						</div>";
 webim_tag4=webim_tag4+"						<div id=\"fls\" node-type=\"fl\" class=\"fl\">";
 webim_tag4=webim_tag4+"							<span class=\"icon_ing\" style=\"display:none;\"/>";
 webim_tag4=webim_tag4+"							<span class=\"wbim_icon_s_photo\" style=\"display:none;\"/>";
 webim_tag4=webim_tag4+"							<p id=\"upFileNameId\"/>";
 webim_tag4=webim_tag4+"						</div>";
 webim_tag4=webim_tag4+"						<div node-type=\"fr\" class=\"fr\">";
 webim_tag4=webim_tag4+"							<a id=\"vdiskId\" href=\"http://vdisk.weibo.com/file/list#3\" target=\"_blank\" class=\"links\" style=\"display:none;\" suda-uatrack=\"key=tblog_webim_behavior&amp;value=view_vdisk\" node-type=\"vdisk\">去我的微盘查看</a>";
 webim_tag4=webim_tag4+"							<a id=\"deleteFileId\" style=\"display:none;\" node-type=\"deleteFile\" class=\"links\">删除</a>";
 webim_tag4=webim_tag4+"						</div>";
 webim_tag4=webim_tag4+"					</div>";
 webim_tag4=webim_tag4+"					<!-- 输入框 -->";
 webim_tag4=webim_tag4+"					<textarea node-type=\"wbim_chat_input_ta\"/>";
 webim_tag4=webim_tag4+"					<textarea id=\"fileUpTextId\" style=\"display:none;\"/>";
 webim_tag4=webim_tag4+"				</div>";
 webim_tag4=webim_tag4+"				";
 webim_tag4=webim_tag4+"				<!-- 最底下一栏(结束对话、发送等) -->";
 webim_tag4=webim_tag4+"				<div node-type=\"wbim_chat_btm\" class=\"wbim_chat_btm\">";
 webim_tag4=webim_tag4+"					<div node-type=\"wbim_chat_btmin_dcp\" class=\"wbim_chat_btmin_dcp\">";
 webim_tag4=webim_tag4+"						<p class=\"wbim_tips_char\">";
 webim_tag4=webim_tag4+"						      还能输入<span style=\"font-size:22px\" node-type=\"wbim_tips_char\">200</span>字";
 webim_tag4=webim_tag4+"						</p>";
 webim_tag4=webim_tag4+"						<div class=\"wbim_chat_btm_rt\">";
 webim_tag4=webim_tag4+"							<div node-type=\"wbim_btn_send\" id=\"webimBtnSendDivId\" class=\"wbim_btn_send wbim_btn_send_disable\"><a id=\"webimBtnSendId\" class=\"wbim_btn_publish\" node-type=\"wbim_btn_publish\">发送</a>";
 webim_tag4=webim_tag4+"								<div class=\"wbim_btn_choose\">";
 webim_tag4=webim_tag4+"									<a class=\"wbim_btn_choose_a\" node-type=\"wbim_btn_choose_a\">选择</a>";
 webim_tag4=webim_tag4+"									<ul node-type=\"wbim_btn_choose\" style=\"display: none;\">";
 webim_tag4=webim_tag4+"										<li node-type=\"wbim_enter_send_li\" class=\"curr\"><span><i></i></span><em><a node-type=\"wbim_enter_send\" href=\"javascript:;\">按Enter键发送</a></em></li>";
 webim_tag4=webim_tag4+"										<li class=\"line\"><span></span><em></em></li>";
 webim_tag4=webim_tag4+"										<li class=\"\" node-type=\"wbim_ctrlenter_send_li\"><span><i></i></span><em><a node-type=\"wbim_ctrlenter_send\" href=\"javascript:;\">按Ctrl+Enter键发送</a></em></li>";
 webim_tag4=webim_tag4+"									</ul>";
 webim_tag4=webim_tag4+"								</div>";
 webim_tag4=webim_tag4+"							</div>";
 webim_tag4=webim_tag4+"						</div>";
 webim_tag4=webim_tag4+"					</div>";
 webim_tag4=webim_tag4+"				</div>";
 webim_tag4=webim_tag4+"		</div>";
 webim_tag4=webim_tag4+"	</div>";
 webim_tag4=webim_tag4+"    </div>";
 webim_tag4=webim_tag4+"	";
 webim_tag4=webim_tag4+"	<div node-type=\"wbim_sys_msg\" style=\"display: none;\" class=\"wbim_sys_msg\">";
 webim_tag4=webim_tag4+"		<div class=\"wbim_sys_tit\">";
 webim_tag4=webim_tag4+"			<div class=\"wbim_sys_tit_lf\" node-type=\"wbim_sys_tit_lf\">系统消息</div>";
 webim_tag4=webim_tag4+"			<a node-type=\"wbim_icon_sys_close\" style=\"float:right;\" href=\"javascript:;\" class=\"wbim_icon_close\"></a>";
 webim_tag4=webim_tag4+"		</div>";
 webim_tag4=webim_tag4+"		<div class=\"wbim_sys_con\" node-type=\"wbim_sys_con\">";
 webim_tag4=webim_tag4+"			<dl node-type=\"wbim_sys_dl\"></dl>";
 webim_tag4=webim_tag4+"		</div>";
 webim_tag4=webim_tag4+"	</div>";
 webim_tag4=webim_tag4+"	<div class=\"wbim_picview_box\" node-type=\"wbim_tips_pos\" style=\"bottom: auto; position: absolute; z-index: 1200; right: 516px; background-color: rgb(243, 243, 243); display: none;\">";
 webim_tag4=webim_tag4+"		<div class=\"wbim_img_con\">";
 webim_tag4=webim_tag4+"			<div class=\"wbim_pic_bar\" node-type=\"wbim_pic_bar\">";
 webim_tag4=webim_tag4+"				<!-- ";
 webim_tag4=webim_tag4+"				<div class=\"wbim_p_ctrl\">";
 webim_tag4=webim_tag4+"					<a class=\"wbim_plft\" node-type=\"turn_left\" title=\"向左转\" href=\"javascript:void(0)\" hidefocus=\"true\"></a>";
 webim_tag4=webim_tag4+"					<span class=\"wbim_vline\">|</span>";
 webim_tag4=webim_tag4+"					<a class=\"wbim_prgt\" node-type=\"turn_right\" title=\"向右转\" href=\"javascript:void(0)\" hidefocus=\"true\"></a>";
 webim_tag4=webim_tag4+"				</div>";
 webim_tag4=webim_tag4+"				-->";
 webim_tag4=webim_tag4+"				<div class=\"wbim_ptit\">";
 webim_tag4=webim_tag4+"						<span id=\"wbim_ptit_id\"></span>";
 webim_tag4=webim_tag4+"				</div>";
 webim_tag4=webim_tag4+"				<a class=\"wbim_pic_bar_cls\" node-type=\"wbim_icon_close_s\" title=\"关闭\" href=\"javascript:closeImgZone();\" hidefocus=\"true\"></a>";
 webim_tag4=webim_tag4+"			</div>";
 webim_tag4=webim_tag4+"			<div id=\"wbim_pic_zoneId\" class=\"wbim_pic_zone\" />";
 webim_tag4=webim_tag4+"		</div>";
 webim_tag4=webim_tag4+"	</div>";
 webim_tag4=webim_tag4+"	<!-- ";
 webim_tag4=webim_tag4+"		<div style=\"position: absolute; z-index: 1500; overflow: hidden; width: 95px; height: 18px; bottom: 119px; right: 360px;\">";
 webim_tag4=webim_tag4+"			<embed id=\"swf_8575\" width=\"95\" height=\"18\" flashvars=\"swfid=1747004125&maxSumSize=50&maxFileSize=50&maxFileNum=1&multiSelect=0&uploadAPI=http%3A%2F%2Fupload.api.weibo.com%2F2%2Fmss%2Fupload.json%3Fsource%3D209678993%26tuid%3D1887188824&initFun=STK.wbim.ui.Upload.initFun&sucFun=STK.wbim.ui.Upload.sucFun&errFun=STK.wbim.ui.Upload.errFun&beginFun=STK.wbim.ui.Upload.beginFun&areaInfo=0-40|10-40&fExt=*.jpg;*.gif;*.jpeg;*.png|*&fExtDec=选择图片|选择文件\" data=\"upload.swf\" wmode=\"transparent\" bgcolor=\"\" allowscriptaccess=\"always\" allowfullscreen=\"true\" scale=\"noScale\" menu=\"false\" type=\"application/x-shockwave-flash\" src=\"http://service.weibo.com/staticjs/tools/upload.swf?v=ef8070fdd05ab2a8\">";
 webim_tag4=webim_tag4+"		</div>";
 webim_tag4=webim_tag4+"	-->";
 webim_tag4=webim_tag4+"	 ";
 webim_tag4=webim_tag4+"</div>";